# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SophonManifestProto.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'SophonManifestProto.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19SophonManifestProto.proto\x12\x17Hi3Helper.Sophon.Protos\"[\n\x13SophonManifestProto\x12\x44\n\x06\x41ssets\x18\x01 \x03(\x0b\x32\x34.Hi3Helper.Sophon.Protos.SophonManifestAssetProperty\"\xb4\x01\n\x1bSophonManifestAssetProperty\x12\x11\n\tAssetName\x18\x01 \x01(\t\x12\x46\n\x0b\x41ssetChunks\x18\x02 \x03(\x0b\x32\x31.Hi3Helper.Sophon.Protos.SophonManifestAssetChunk\x12\x11\n\tAssetType\x18\x03 \x01(\x05\x12\x11\n\tAssetSize\x18\x04 \x01(\x03\x12\x14\n\x0c\x41ssetHashMd5\x18\x05 \x01(\t\"\x9c\x01\n\x18SophonManifestAssetChunk\x12\x11\n\tChunkName\x18\x01 \x01(\t\x12 \n\x18\x43hunkDecompressedHashMd5\x18\x02 \x01(\t\x12\x19\n\x11\x43hunkOnFileOffset\x18\x03 \x01(\x03\x12\x11\n\tChunkSize\x18\x04 \x01(\x03\x12\x1d\n\x15\x43hunkSizeDecompressed\x18\x05 \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SophonManifestProto_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SOPHONMANIFESTPROTO']._serialized_start=54
  _globals['_SOPHONMANIFESTPROTO']._serialized_end=145
  _globals['_SOPHONMANIFESTASSETPROPERTY']._serialized_start=148
  _globals['_SOPHONMANIFESTASSETPROPERTY']._serialized_end=328
  _globals['_SOPHONMANIFESTASSETCHUNK']._serialized_start=331
  _globals['_SOPHONMANIFESTASSETCHUNK']._serialized_end=487
# @@protoc_insertion_point(module_scope)
