# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sophon/proto/SophonPatchProto.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sophon/proto/SophonPatchProto.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#sophon/proto/SophonPatchProto.proto\x12\x17Hi3Helper.Sophon.Protos\"\xa4\x01\n\x10SophonPatchProto\x12\x46\n\x0bPatchAssets\x18\x01 \x03(\x0b\x32\x31.Hi3Helper.Sophon.Protos.SophonPatchAssetProperty\x12H\n\x0cUnusedAssets\x18\x02 \x03(\x0b\x32\x32.Hi3Helper.Sophon.Protos.SophonUnusedAssetProperty\"\x99\x01\n\x18SophonPatchAssetProperty\x12\x11\n\tAssetName\x18\x01 \x01(\t\x12\x11\n\tAssetSize\x18\x02 \x01(\x03\x12\x14\n\x0c\x41ssetHashMd5\x18\x03 \x01(\t\x12\x41\n\nAssetInfos\x18\x04 \x03(\x0b\x32-.Hi3Helper.Sophon.Protos.SophonPatchAssetInfo\"i\n\x14SophonPatchAssetInfo\x12\x12\n\nVersionTag\x18\x01 \x01(\t\x12=\n\x05\x43hunk\x18\x02 \x01(\x0b\x32..Hi3Helper.Sophon.Protos.SophonPatchAssetChunk\"\xed\x01\n\x15SophonPatchAssetChunk\x12\x11\n\tPatchName\x18\x01 \x01(\t\x12\x12\n\nVersionTag\x18\x02 \x01(\t\x12\x0f\n\x07\x42uildId\x18\x03 \x01(\t\x12\x11\n\tPatchSize\x18\x04 \x01(\x03\x12\x10\n\x08PatchMd5\x18\x05 \x01(\t\x12\x13\n\x0bPatchOffset\x18\x06 \x01(\x03\x12\x13\n\x0bPatchLength\x18\x07 \x01(\x03\x12\x18\n\x10OriginalFileName\x18\x08 \x01(\t\x12\x1a\n\x12OriginalFileLength\x18\t \x01(\x03\x12\x17\n\x0fOriginalFileMd5\x18\n \x01(\t\"s\n\x19SophonUnusedAssetProperty\x12\x12\n\nVersionTag\x18\x01 \x01(\t\x12\x42\n\nAssetInfos\x18\x02 \x03(\x0b\x32..Hi3Helper.Sophon.Protos.SophonUnusedAssetInfo\"W\n\x15SophonUnusedAssetInfo\x12>\n\x06\x41ssets\x18\x01 \x03(\x0b\x32..Hi3Helper.Sophon.Protos.SophonUnusedAssetFile\"L\n\x15SophonUnusedAssetFile\x12\x10\n\x08\x46ileName\x18\x01 \x01(\t\x12\x10\n\x08\x46ileSize\x18\x02 \x01(\x03\x12\x0f\n\x07\x46ileMd5\x18\x03 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sophon.proto.SophonPatchProto_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SOPHONPATCHPROTO']._serialized_start=65
  _globals['_SOPHONPATCHPROTO']._serialized_end=229
  _globals['_SOPHONPATCHASSETPROPERTY']._serialized_start=232
  _globals['_SOPHONPATCHASSETPROPERTY']._serialized_end=385
  _globals['_SOPHONPATCHASSETINFO']._serialized_start=387
  _globals['_SOPHONPATCHASSETINFO']._serialized_end=492
  _globals['_SOPHONPATCHASSETCHUNK']._serialized_start=495
  _globals['_SOPHONPATCHASSETCHUNK']._serialized_end=732
  _globals['_SOPHONUNUSEDASSETPROPERTY']._serialized_start=734
  _globals['_SOPHONUNUSEDASSETPROPERTY']._serialized_end=849
  _globals['_SOPHONUNUSEDASSETINFO']._serialized_start=851
  _globals['_SOPHONUNUSEDASSETINFO']._serialized_end=938
  _globals['_SOPHONUNUSEDASSETFILE']._serialized_start=940
  _globals['_SOPHONUNUSEDASSETFILE']._serialized_end=1016
# @@protoc_insertion_point(module_scope)
